In [201]:
import pandas as pd
import numpy as np

In [202]:
df = pd.read_csv('try2.csv')
df.head()

,frame,ankle.L@x,ankle.L@y,ankle.L@z,ankle.R@x,ankle.R@y,ankle.R@z,background@x,background@y,background@z,...,thumb_middle.L@z,thumb_middle.R@x,thumb_middle.R@y,thumb_middle.R@z,thumb_up.L@x,thumb_up.L@y,thumb_up.L@z,thumb_up.R@x,thumb_up.R@y,thumb_up.R@z
0,1,-1.42455,0.753268,1.997,-1.42455,0.753268,1.997,NaN,NaN,NaN,...,-330.8189,-0.246929,-0.229381,0.944,108.3979,-4.5922,-330.8189,-0.252367,-0.25109,0.981
1,2,-1.42455,0.753268,1.997,-1.42455,0.753268,1.997,NaN,NaN,NaN,...,-330.8189,-0.246929,-0.229381,0.944,108.3979,-4.5922,-330.8189,-0.252367,-0.25109,0.981
2,3,-1.42455,0.753268,1.997,-1.42455,0.753268,1.997,NaN,NaN,NaN,...,-330.8189,-0.246929,-0.229381,0.944,108.3979,-4.5922,-330.8189,-0.252367,-0.25109,0.981
3,4,-1.42455,0.753268,1.997,-1.42455,0.753268,1.997,NaN,NaN,NaN,...,-330.8189,-0.246929,-0.229381,0.944,108.3979,-4.5922,-330.8189,-0.252367,-0.25109,0.981
4,5,-1.42455,0.753268,1.997,-1.42455,0.753268,1.997,NaN,NaN,NaN,...,-330.8189,-0.246929,-0.229381,0.944,108.3979,-4.5922,-330.8189,-0.252367,-0.25109,0.981

In [203]:
joints_R ={0:"hand_bottom.R@y",
	1:"palm_thumb.R@y",
	2:"thumb_lower.R@y",
	3:"thumb_middle.R@y",
	4:"thumb_up.R@y",
	5:"palm_index.R@y",
	6:"index_lower.R@y",
	7:"index_middle.R@y",
	8:"index_up.R@y",
	9:"palm_middle.R@y",
	10:"middle_lower.R@y",
	11:"middle_middle.R@y",
	12:"middle_up.R@y",
	13:"palm_ring.R@y",
	14:"ring_lower.R@y",
	15:"ring_middle.R@y",
	16:"ring_up.R@y",
	17:"palm_pinky.R@y",
	18:"pinky_lower.R@y",
	19:"pinky_middle.R@y",
	20:"pinky_up.R@y"}

In [204]:
joints_L ={0:"hand_bottom.L@z",
	1:"palm_thumb.L@z",
	2:"thumb_lower.L@z",
	3:"thumb_middle.L@z",
	4:"thumb_up.L@z",
	5:"palm_index.L@z",
	6:"index_lower.L@z",
	7:"index_middle.L@z",
	8:"index_up.L@z",
	9:"palm_middle.L@z",
	10:"middle_lower.L@z",
	11:"middle_middle.L@z",
	12:"middle_up.L@z",
	13:"palm_ring.L@z",
	14:"ring_lower.L@z",
	15:"ring_middle.L@z",
	16:"ring_up.L@z",
	17:"palm_pinky.L@z",
	18:"pinky_lower.L@z",
	19:"pinky_middle.L@z",
	20:"pinky_up.L@z",
    21:"elbow.L@z",
          22:"wrist.L@z"}

In [205]:
rotate_list = {
	1:"palm_thumb.L@",
	2:"thumb_lower.L@",
	3:"thumb_middle.L@",
	4:"thumb_up.L@",
	5:"palm_index.L@",
	6:"index_lower.L@",
	7:"index_middle.L@",
	8:"index_up.L@",
	9:"palm_middle.L@",
	10:"middle_lower.L@",
	11:"middle_middle.L@",
	12:"middle_up.L@",
	13:"palm_ring.L@",
	14:"ring_lower.L@",
	15:"ring_middle.L@",
	16:"ring_up.L@",
	17:"palm_pinky.L@",
	18:"pinky_lower.L@",
	19:"pinky_middle.L@",
	20:"pinky_up.L@",
21:"hand_bottom.L@"}

In [206]:
all_vals = list(rotate_list.values())
h_x="wrist.L@x"
h_y="wrist.L@y"
h_z="wrist.L@z"
for col in all_vals:
    temp_x = col+"x"
    temp_y = col+"y" 
    temp_z = col+"z" 
    
    rel_x = df[temp_x] - df[h_x]
    rel_y = df[temp_y] - df[h_y]
    
    df[temp_y] = rel_y*np.cos(np.pi/3)  - rel_x*np.sin(np.pi/3) + df[h_y]
    df[temp_x] = rel_y*np.sin(np.pi/3)  + rel_x*np.cos(np.pi/3) + df[h_x]

In [207]:
df.to_csv('try3.csv', index = False)